Задание 3
Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 6],
             [2, 8],
             [3, 11],
             [3, 10],
             [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [3]:
mean_a = np.array([a[:, 0].mean(), a[:, 1].mean()])
mean_a

array([2. , 8.4])

In [13]:
a_centered = np.subtract(a, mean_a) #broadcasting
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [15]:
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])
print(f'a_centered_sp / (N - 1): {a_centered_sp / (a_centered.shape[0] - 1)}')

a_centered_sp / (N - 1): 2.0
